spring.application.name=nutri-express

# Conexão com o PostgreSQL que está rodando no Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/nutridb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Faz o Hibernate criar/atualizar a tabela 'pratos' automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
